---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "47"
year: "2025"
contributor: 
- Ulrike Wuttke
title: "<q>Das ist ja nur die Spitze des Eisbergs!</q>"
subtitle: "Bericht vom Workshop zum Datentracking in der Wissenschaft im Vorfeld der ISI 2025, 17.03.2025 (TU Chemnitz)"
pdf: "main.pdf"
doi: "10.18452/x"
date: 2025-09-20
comments: false
sharing: true
footer: true

---