---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "47"
year: "2025"
contributor: 
- Redaktion LIBREAS
title: "Editorial #47: Lug und Trug (im Wissenschaftssystem)"
pdf: "main.pdf"
doi: "10.18452/x"
date: 2025-09-20
comments: false
sharing: true
footer: true

---