---

layout: page
lang: "en"
journal: "LIBREAS. Library Ideas"
issue: "47"
year: "2025"
contributor: 
- Anna Abalkina
title: "Journal hijacking: challenges for the scientific community and recommendations for journals"
pdf: "main.pdf"
doi: "10.18452/x"
date: 2025-09-20
comments: false
sharing: true
footer: true

---