---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "47"
year: "2025"
contributor: 
- Redaktion LIBREAS
title: "Das liest die LIBREAS, Nummer #16 (Frühling–Sommer 2025)"
pdf: "https://doi.org/10.18452/34782"
doi: "10.18452/34782"
date: 2025-10-20
comments: false
sharing: true
footer: true

---