---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "47"
year: "2025"
contributor: 
- Redaktion LIBREAS
title: "Das liest die LIBREAS, Nummer #16 (Fühling–Sommer 2025)"
pdf: "main.pdf"
doi: "10.18452/x"
date: 2025-09-20
comments: false
sharing: true
footer: true

---