---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "47"
year: "2025"
contributor: 
- Ben Kaden
title: "Edit this!: LIBREAS ist 20 und schreibt sich in die Wikipedia. Ein fröhlich-reflexiver Bericht"
pdf: "main.pdf"
doi: "10.18452/x"
date: 2025-09-20
comments: false
sharing: true
footer: true

---