---

layout: page
lang: "en"
journal: "LIBREAS. Library Ideas"
issue: "47"
year: "2025"
contributor: 
- Salim Moussa
title: "Lost in retraction: The curious case of a misidentified investigation and a missing retraction notice"
abstract: "This commentary examines the unusual retraction record of an article in the Journal of Marketing Research, an elite marketing journal, that was originally retracted in 2014 but whose retraction notice went missing from Sage Publications’ scholarly record until a second retraction in 2022. To make matters worse, the retraction notice incorrectly identified Tilburg University as the investigating institution, rather than Erasmus University Rotterdam. These discrepancies raise serious questions about editorial oversight, transparency, and academic record integrity. By analyzing this case, the author emphasizes the need for stricter retraction protocols to maintain scientific integrity."
pdf: "https://doi.org/10.18452/34822"
doi: "10.18452/34822"
date: 2025-10-20
comments: false
sharing: true
footer: true

---